### ISSUE TITLE
Milestone 3 todo for tin 

### ISSUE THREAD

**Issue by tinnytintin10** [syoung20/cs326-final-upsilon#11]
- [x]  Fix front end spelling 

- [x] Fix add ingredients bug on the create recipe form #10 

- [x] Figure out how to upload an image with the form #12 

- [x] Craft SQL calls for the `/search` API endpoint #13 

- [x] Craft SQL calls for the `/recipes` endpoint #15 

- [ ] figure out how we are going to track if a user is logged in (talk to the team about that) and implement the agreed-upon strategy  

Check-in with teammates to see if there is anything else left to do.
