### ISSUE TITLE
Milestone 2 part 2: Front-end implementation

### ISSUE THREAD

**Issue by tinnytintin10** [syoung20/cs326-final-upsilon#3]
# Front-end implementation

Instructor Notes... 

> This issue is for us to collaborate on and track progress towards one part of the milestone. Once all of the bullets are complete on all the issues with the milestone 2 label and the issues are closed out, we'll be ready to push out the release. 

ToDos 

- [x] Identify all the points in the UI that CRUD operations will take place 
- [x] Develop the client-side scripts that will get this data and send it to the server 
- [x] Once done, take four screenshots with a brief description of our user interface to illustrate each of the crud operations and include them in docs/milestone2.md

@syoung20 @Nikon-knon

**Comment by tinnytintin10** [comment]
# CREATE 

The two screenshots below highlight the Create part of the CRUD operation our web-app performs. 

![Screen Shot 2020-04-24 at 10 47 18 PM](https://user-images.githubusercontent.com/53792284/80269423-cd341d00-867d-11ea-8780-dac31cef6fdf.png)

`console.log` of the form data server-side. Note, the data is not real recipe data 

![Screen Shot 2020-04-24 at 10 47 49 PM](https://user-images.githubusercontent.com/53792284/80269440-efc63600-867d-11ea-9ba3-896f2bea8a94.png)

**Comment by tinnytintin10** [comment]
# READ

Below is an example of a read operation. The user searches for something and the result is displayed.Note dummy JSON data is sent back. 

![Screen Shot 2020-04-24 at 10 51 33 PM](https://user-images.githubusercontent.com/53792284/80269512-59dedb00-867e-11ea-80bd-cacd31201079.png)
![Screen Shot 2020-04-24 at 10 51 58 PM](https://user-images.githubusercontent.com/53792284/80269517-5ea38f00-867e-11ea-8193-ad77b36cf2b1.png)

**Comment by syoung20** [comment]
The following is an example of a delete operation. A user can delete a recipe category from their recipe book.
![Screen Shot 2020-04-24 at 9 59 25 PM](https://user-images.githubusercontent.com/44949568/80269689-86432900-8677-11ea-89c3-d0b17487fa0e.png)

Below is another example of a delete operation, in which the user can remove a specific recipe from their recipe collection.
![Screen Shot 2020-04-24 at 9 59 50 PM](https://user-images.githubusercontent.com/44949568/80269693-8c390a00-8677-11ea-97f8-d79a794c9efd.png)

This is an example of an update operation. A user can update the title of a category of their pantry inventory, and can also update the items in that category.
![Screen Shot 2020-04-24 at 10 00 19 PM](https://user-images.githubusercontent.com/44949568/80269701-94914500-8677-11ea-8c22-a6222e17313f.png)

**Comment by Nikon-knon** [comment]
The following is an example of a read operation to show a recipe on recipe.html
![image](https://user-images.githubusercontent.com/55409182/80270662-11c4b600-8688-11ea-8e29-9eceed51aebc.png)

This is the json object recieved after the fetch call:
![image](https://user-images.githubusercontent.com/55409182/80270683-49336280-8688-11ea-8eab-30ac0f1acb0d.png)
